export default {
    OPEN_CASH_DIALOG: 'app/OPEN_CASH_DIALOG',
    CLOSE_CASH_DIALOG: 'app/CLOSE_CASH_DIALOG',
    SEARCH_RESULTS_REQUESTED: 'marketWatch/SEARCH_RESULTS_REQUESTED',
    SEARCH_RESULTS_SUCCEEDED: 'marketWatch/SEARCH_RESULTS_SUCCEEDED',
    SEARCH_RESULTS_FAILED: 'marketWatch/SEARCH_RESULTS_FAILED',
    ADD_STOCK_REQUESTED: 'marketWatch/ADD_STOCK_REQUESTED',
    ADD_STOCK_SUCCEEDED: 'marketWatch/ADD_STOCK_SUCCEEDED',
    FETCH_EXISTING_STOCKS: 'marketWatch/FETCH_EXISTING_STOCKS',
    EXISTING_STOCKS_FETCHED: 'marketWatch/EXISTING_STOCKS_FETCHED',
    CLEAR_SEARCH_RESULTS: 'marketWatch/CLEAR_SEARCH_RESULTS',
    REMOVE_EXISTING_STOCK: 'marketWatch/REMOVE_EXISTING_STOCK'
};
